---
apiVersion: v2
appVersion: v1.2.20
description: Kanboard is a free and open source Kanban project management software.
name: kanboard
version: 8.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - kanboard
  - kanban
home: https://github.com/bjw-s/charts/tree/master/charts/stable/kanboard
icon: https://raw.githubusercontent.com/kanboard/website/master/assets/img/icon.svg
sources:
  - https://github.com/kanboard/kanboard
maintainers:
  - name: trly
    email: trly@users.noreply.github.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.4.0
  - name: postgresql
    version: 13.2.8
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
