---
apiVersion: v2
appVersion: v2.7.7
description: A Python based monitoring and tracking tool for Plex Media Server
name: tautulli
version: 11.4.3
kubeVersion: ">=1.16.0-0"
keywords:
  - tautulli
  - plex
home: https://github.com/bjw-s/charts/tree/master/charts/stable/tautulli
icon: https://github.com/Tautulli/Tautulli/blob/master/data/interfaces/default/images/logo.png?raw=true
sources:
  - https://github.com/Tautulli/Tautulli
  - https://github.com/bjw-s/container-images
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
