---
apiVersion: v2
appVersion: "4.2.0"
description: The Lounge, modern web IRC client designed for self-hosting
name: thelounge
version: 4.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - thelounge
  - IRC
  - "The Lounge"
  - docker
  - thelounge-docker
home: https://github.com/bjw-s/charts/tree/master/charts/stable/thelounge
icon: https://avatars.githubusercontent.com/u/14336958?s=200&v=4
sources:
  - https://github.com/thelounge/thelounge
maintainers:
  - name: Rwaltr
    email: rwalt@pm.me
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
