---
apiVersion: v2
appVersion: v3.0.8.1507
description: Smart PVR for newsgroup and bittorrent users
name: sonarr
version: 17.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - sonarr
  - torrent
  - usenet
home: https://github.com/bjw-s/charts/tree/master/charts/stable/sonarr
icon: https://github.com/Sonarr/Sonarr/blob/phantom-develop/Logo/512.png?raw=true
sources:
  - https://github.com/Sonarr/Sonarr
  - https://github.com/bjw-s/container-images
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.4.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
