---
apiVersion: v2
appVersion: v1.23.4
description: "A self-hosted data logger for your Tesla \U0001F698"
name: teslamate
version: 9.1.0
keywords:
  - teslamate
  - tesla
home: https://github.com/bjw-s/charts/tree/master/charts/stable/teslamate
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Tesla_Motors.svg/793px-Tesla_Motors.svg.png
sources:
  - https://github.com/adriankumpf/teslamate
  - https://github.com/bjw-s/charts/tree/master/charts/stable/teslamate
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.4.0
  - name: postgresql
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
maintainers:
  - name: billimek
    email: jeff@billimek.com
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
