---
apiVersion: v2
appVersion: v0.2.4
description: A PowerDNS web interface with advanced features
name: powerdns-admin
version: 2.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - powerdns
  - pdns
  - powerdns-admin
  - admin
home: https://github.com/bjw-s/charts/tree/master/charts/stable/powerdns-admin
sources:
  - https://github.com/PowerDNS-Admin/PowerDNS-Admin
maintainers:
  - name: psych0d0g
    email: psych0d0g@users.noreply.github.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
