---
apiVersion: v2
appVersion: v0.1.0.715
description: A fork of Radarr to work with Books & AudioBooks
name: readarr
version: 7.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - readarr
  - torrent
  - usenet
  - AudioBooks
  - ebooks
home: https://github.com/bjw-s/charts/tree/master/charts/stable/readarr
icon: https://readarr.com/img/logo.png
sources:
  - https://github.com/Readarr/Readarr
  - https://github.com/bjw-s/container-images
maintainers:
  - name: mcmarkj
    email: mark@markmcw.uk
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
