---
apiVersion: v2
name: comcast
version: 6.4.3
appVersion: 1.0.0
description: periodic comcast data usage checks and save the results to InfluxDB
keywords:
  - comcast
  - influxdb
  - xfinity
home: https://github.com/bjw-s/charts/tree/master/charts/stable/comcast
icon: https://i.imgur.com/iR1dUpp.png
sources:
  - https://github.com/billimek/comcastUsage-for-influxdb
  - https://github.com/bjw-s/charts
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
