---
apiVersion: v2
appVersion: v0.5.2
description: Maddy Mail Server
name: maddy
version: 5.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - maddy
  - mail
home: https://github.com/bjw-s/charts/tree/master/charts/stable/maddy
# Project has no icon yet
# icon: https://maddy.org/icon
sources:
  - https://github.com/foxcpp/maddy
maintainers:
  - name: angelnu
    email: git@angelnu.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
  - name: postgresql
    version: 12.12.4
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
