---
apiVersion: v2
appVersion: v0.5.2
description: Maddy Mail Server
name: maddy
version: 3.2.2
kubeVersion: ">=1.16.0-0"
keywords:
  - maddy
  - mail
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/maddy
# Project has no icon yet
# icon: https://maddy.org/icon
sources:
  - https://github.com/foxcpp/maddy
maintainers:
  - name: angelnu
    email: git@angelnu.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 4.5.2
  - name: postgresql
    version: 11.9.13
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
