---
apiVersion: v2
appVersion: v22.07.2
description: A dead simple static HOMepage for your servER to keep your services on hand, from a simple yaml configuration file.
icon: https://raw.githubusercontent.com/bastienwirtz/homer/main/public/logo.png
home: https://github.com/bjw-s/charts/tree/master/charts/stable/homer
name: homer
version: 8.0.3
kubeVersion: ">=1.16.0-0"
sources:
  - https://github.com/bastienwirtz/homer
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
