---
apiVersion: v2
appVersion: v2009.1.0
description: Booksonic is a platform for accessing the audibooks you own wherever you are
name: booksonic-air
version: 6.4.3
kubeVersion: ">=1.16.0-0"
keywords:
  - booksonic
  - audiobook
home: https://github.com/bjw-s/charts/tree/master/charts/stable/booksonic-air
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/booksonic-air.png
sources:
  - https://github.com/popeen/Booksonic-Air
  - https://hub.docker.com/r/linuxserver/booksonic-air
maintainers:
  - name: wojoinc
    email: wojoinc@pm.me
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
