---
apiVersion: v2
appVersion: 1.18.2
description: Open Source Continuous File Synchronization
name: syncthing
version: 4.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - syncthing
  - file sync
home: https://github.com/bjw-s/charts/tree/master/charts/stable/syncthing
icon: https://github.com/syncthing/syncthing/raw/main/assets/logo-128.png
sources:
  - https://syncthing.net/
  - https://github.com/syncthing/syncthing
maintainers:
  - name: FlipEnergy
    email: dennis.zhang.nrg@gmail.com
  - name: claughinghouse
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
