---
apiVersion: v2
appVersion: 1.0.0
description: LanCache Monolithic - a caching proxy server for game download content
name: lancache
version: 1.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - lancache
home: https://github.com/bjw-s/charts/tree/master/charts/stable/lancache
icon: https://avatars.githubusercontent.com/u/16938914
sources:
  - https://github.com/lancachenet/monolithic
  - https://hub.docker.com/r/lancachenet/monolithic
  - https://hub.docker.com/r/lancachenet/lancache-dns
maintainers:
  - name: reitermarkus
    email: me@reitermark.us
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
