---
apiVersion: v2
appVersion: latest
description: snapcast helm package
name: snapcast
version: 0.1.3
kubeVersion: ">=1.16.0-0"
keywords:
  - snapcast
  - snapserver
home: https://github.com/bjw-s/charts/tree/master/charts/incubator/snapcast
icon: https://github.com/badaix/snapcast/blob/master/doc/web_hi_res_512.png
sources:
  - https://github.com/badaix/snapcast
maintainers:
  - name: lanquarden
    email: lanquarden@gmail.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
