---
apiVersion: v2
appVersion: 0.9.0
description: Focalboard is an open source, self-hosted alternative to Trello, Notion, and Asana.
name: focalboard
version: 5.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - focalboard
  - kanban
  - project management
home: https://github.com/bjw-s/charts/tree/master/charts/stable/focalboard
icon: https://github.com/mattermost/focalboard/raw/main/webapp/static/favicon.svg
sources:
  - https://www.focalboard.com/
  - https://github.com/mattermost/focalboard
  - https://github.com/FlipEnergy/container-images/blob/main/focalboard
maintainers:
  - name: FlipEnergy
    email: dennis.zhang.nrg@gmail.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.4.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
