---
apiVersion: v2
appVersion: 1.4.3
description: Create live TV channel streams from media on your Plex servers.
name: dizquetv
version: 5.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - dizqueTV
  - dizquetv
home: https://github.com/bjw-s/charts/tree/master/charts/stable/dizquetv
icon: https://github.com/vexorian/dizquetv/raw/main/resources/dizquetv.png?raw=true
sources:
  - https://github.com/vexorian/dizquetv
  - https://hub.docker.com/r/vexorian/dizquetv
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
