---
apiVersion: v2
appVersion: v21.1
description: NZBGet is a Usenet downloader client
name: nzbget
version: 13.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - nzbget
  - usenet
home: https://github.com/bjw-s/charts/tree/master/charts/stable/nzbget
icon: https://avatars1.githubusercontent.com/u/3368377?s=400&v=4
sources:
  - https://nzbget.net/
  - https://github.com/bjw-s/container-images
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.4.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
