---
apiVersion: v2
appVersion: 0.8.0
description: Baïkal is a lightweight CalDAV+CardDAV server. It offers a web interface with management of users, address books and calendars.
name: baikal
version: 5.3.0
kubeVersion: ">=1.16.0-0"
keywords:
  - baikal
  - caldav
  - carddav
  - contacts
  - calendar
home: https://github.com/bjw-s/charts/tree/master/charts/stable/baikal
icon: https://avatars.githubusercontent.com/u/28524376?s=400&v=4
sources:
  - https://github.com/sabre-io/Baikal
  - https://github.com/ckulka/baikal-docker
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.0
  - name: mariadb
    version: 11.5.7
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
