---
apiVersion: v2
appVersion: 1.0.0
description: Searx is a privacy-respecting, hackable metasearch engine
name: searx
version: 5.6.3
kubeVersion: ">=1.16.0-0"
keywords:
  - searx
  - search engine
  - privacy
home: https://github.com/bjw-s/charts/tree/master/charts/stable/searx
icon: https://github.com/searx/searx/blob/master/searx/static/themes/simple/img/logo_searx_a.png?raw=true
sources:
  - https://github.com/searx/searx
  - https://searx.github.io/searx/
  - https://hub.docker.com/r/searx/searx
maintainers:
  - name: auricom
    email: bjw-s@xpander.eml.cc
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
