---
apiVersion: v2
appVersion: 1.8.0
description: Paperless - Index and archive all of your scanned paper documents
name: paperless
version: 13.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - paperless
home: https://github.com/bjw-s/charts/tree/master/charts/stable/paperless
icon: https://avatars.githubusercontent.com/u/47271576?s=200&v=4
sources:
  - https://github.com/paperless-ngx/paperless-ngx
maintainers:
  - name: mr-onion-2
  - name: jonnobrow
    email: jonathan@jonnobrow.co.uk
  - name: morremeyer
    email: charts@mor.re
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
  - name: postgresql
    version: 13.2.27
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.17.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
