---
apiVersion: v2
appVersion: latest
description: rTorrent is a stable, high-performance and low resource consumption BitTorrent client.
name: rtorrent-flood
version: 10.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - rtorrent
  - flood
  - torrent
home: https://github.com/bjw-s/charts/tree/master/charts/stable/rtorrent-flood
icon: https://github.com/jfurrow/flood/blob/master/flood.png?raw=true
sources:
  - https://github.com/jesec/rtorrent
  - https://github.com/jesec/flood
  - https://hub.docker.com/r/jesec/rtorrent
  - https://hub.docker.com/r/jesec/flood
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
