---
apiVersion: v2
appVersion: latest
description: mopidy helm package
name: mopidy
version: 1.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - mopidy
home: https://github.com/bjw-s/charts/tree/master/charts/stable/mopidy
icon: https://mopidy.org/icon
sources:
  - https://github.com/mopidy/mopidy-docker
maintainers:
  - name: lanquarden
    email: lanquarden@gmail.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
