---
apiVersion: v2
appVersion: v0.18
description: DNS proxy as ad-blocker for local network
name: blocky
version: 13.1.0
kubeVersion: ">=1.19.0-0"
keywords:
  - blocky
  - adblock
  - dns
home: https://github.com/bjw-s/charts/tree/master/charts/stable/blocky
icon: https://github.com/0xERR0R/blocky/raw/master/docs/blocky.svg?sanitize=true
sources:
  - https://github.com/0xERR0R/blocky
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.6.2
    condition: redis.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `redis` chart dependency to version 17.1.7
