---
apiVersion: v2
appVersion: V.2.2.0
description: Track your cryptocurrency holdings/portfolio
name: cryptofolio
version: 1.4.2
kubeVersion: ">=1.16.0-0"
keywords:
  - cryptofolio
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/cryptofolio
icon: https://raw.githubusercontent.com/Xtrendence/Cryptofolio/main/website/assets/img/Logo.png
sources:
  - https://github.com/Xtrendence/cryptofolio
maintainers:
  - name: dvmrry
    email: github@mrry.io
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
