---
apiVersion: v2
appVersion: v0.9.0
description: An exporter for metrics in the InfluxDB format, transforms them and exposes them for consumption by Prometheus.
name: influxdb-exporter
version: 2.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - influxdb-exporter
home: https://github.com/bjw-s/charts/tree/master/charts/incubator/influxdb-exporter
icon: https://influxdata.github.io/branding/img/downloads/influxdata-logo--symbol--pool.jpg
sources:
  - https://github.com/prometheus/influxdb_exporter
maintainers:
  - name: Aste88
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
