---
apiVersion: v2
appVersion: v0.20.1316
description: API Support for your favorite torrent trackers
name: jackett
version: 12.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - jackett
  - torrent
home: https://github.com/bjw-s/charts/tree/master/charts/stable/jackett
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/jackett-banner.png
sources:
  - https://github.com/Jackett/Jackett
  - https://github.com/bjw-s/container-images
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
