---
apiVersion: v2
appVersion: 3.10-0.9.8-0.13.8
description: ruTorrent is a popular rtorrent client with a webui for ease of use.
name: rtorrent-rutorrent
version: 2.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - rutorrent
  - torrrent
home: https://github.com/bjw-s/charts/tree/master/charts/stable/rtorrent-rutorrent
icon: https://avatars.githubusercontent.com/u/88781313?s=200&v=4
sources:
  - https://github.com/Novik/ruTorrent
maintainers:
  - name: funkypenguin
    email: davidy@funkypenguin.co.nz
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
