---
apiVersion: v2
appVersion: v4.4.2
description: qBittorrent is a cross-platform free and open-source BitTorrent client
name: qbittorrent
version: 14.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - qbittorrent
  - torrrent
home: https://github.com/bjw-s/charts/tree/master/charts/stable/qbittorrent
icon: https://cloud.githubusercontent.com/assets/14862437/23586868/89ef2922-01c4-11e7-869c-52aafcece17f.png
sources:
  - https://github.com/qbittorrent/qBittorrent
  - https://github.com/bjw-s/container-images
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
