---
apiVersion: v2
appVersion: 2.1.2
description: This server allows you to sync any Joplin client
name: joplin-server
version: 7.0.1
keywords:
  - joplin
  - notes
home: https://github.com/bjw-s/charts/tree/master/charts/stable/jopplin-server
icon: https://raw.githubusercontent.com/laurent22/joplin/master/Assets/LinuxIcons/256x256.png?raw=true
sources:
  - https://github.com/laurent22/joplin/tree/dev/packages/server
  - https://github.com/laurent22/joplin
  - https://hub.docker.com/r/joplin/server
maintainers:
  - name: auricom
    email: bjw-s@xpander.eml.cc
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
  - name: postgresql
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
