---
apiVersion: v2
appVersion: 2.7.1
description: A web-based collaborative LaTeX editor
name: overleaf
version: 6.2.0
kubeVersion: ">=1.16.0-0"
keywords:
  - overleaf
  - sharelatex
home: https://github.com/bjw-s/charts/tree/master/charts/stable/overleaf
icon: https://avatars.githubusercontent.com/u/6359919?s=200&v=4
sources:
  - https://github.com/overleaf/overleaf
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
  - name: redis
    version: 17.17.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: mongodb
    version: 13.18.4
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `redis` chart dependency to version 16.13.2
