---
apiVersion: v2
appVersion: v3.3.1
description: Free and easy binary newsreader
name: sabnzbd
version: 10.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - sabnzbd
  - usenet
home: https://github.com/bjw-s/charts/tree/master/charts/stable/sabnzbd
icon: https://avatars1.githubusercontent.com/u/960698?s=400&v=4
sources:
  - https://sabnzbd.org/
  - https://github.com/bjw-s/container-images
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
