---
apiVersion: v2
appVersion: v3.00
description: Transmission is a cross-platform BitTorrent client
name: transmission
version: 8.4.4
kubeVersion: ">=1.16.0-0"
keywords:
  - transmission
  - torrent
home: https://github.com/bjw-s/charts/tree/master/charts/stable/transmission
icon: https://raw.githubusercontent.com/transmission/transmission/main/extras/transmission-1920.jpg
sources:
  - https://github.com/transmission/transmission
  - https://github.com/bjw-s/container-images
maintainers:
  - name: ishioni
    email: helm@movishell.pl
  - name: bjw-s
    email: me@bjw-s.dev
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Fixed icon URL
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
