---
apiVersion: v2
appVersion: 4.16.12
description: Want a Movie or TV Show on Plex or Emby? Use Ombi!
name: ombi
version: 11.5.2
kubeVersion: ">=1.16.0-0"
keywords:
  - ombi
  - plex
  - emby
  - sonarr
  - radarr
  - couchpotato
home: https://github.com/bjw-s/charts/tree/master/charts/stable/ombi
icon: https://github.com/tidusjar/Ombi/blob/feature/v4/src/Ombi/wwwroot/images/ms-icon-310x310.png?raw=true
sources:
  - https://github.com/tidusjar/Ombi
  - https://hub.docker.com/r/linuxserver/ombi
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
