---
apiVersion: v2
appVersion: latest
description: HTPC/Homelab Services Organizer
name: organizr
version: 8.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - organizr
home: https://github.com/bjw-s/charts/tree/master/charts/stable/organizr
icon: https://github.com/causefx/Organizr/blob/v2-master/plugins/images/organizr/logo.png?raw=true
sources:
  - https://github.com/causefx/Organizr
  - https://hub.docker.com/r/organizr/organizr
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
