---
apiVersion: v2
appVersion: 1.25.2
description: Vaultwarden is a Bitwarden compatable server in Rust
name: vaultwarden
version: 6.2.0
kubeVersion: ">=1.16.0-0"
keywords:
  - Vaultwarden
  - bitwardenrs
home: "https://github.com/bjw-s/charts/tree/master/charts/stable/vaultwarden"
icon: "https://sesoodan.sirv.com/bitwarden_rs.png"
sources:
  - https://github.com/dani-garcia/vaultwarden
maintainers:
  - name: Rwaltr
    email: rwalt@pm.me
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
  - name: mariadb
    version: 11.5.7
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: postgresql
    version: 12.12.4
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
