---
apiVersion: v2
appVersion: 2.0.36
description: Miniflux is a minimalist and opinionated feed reader.
name: miniflux
version: 7.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - miniflux
  - rss
  - news
home: https://github.com/bjw-s/charts/tree/master/charts/miniflux
icon: https://raw.githubusercontent.com/miniflux/logo/master/icon.svg
sources:
  - https://github.com/miniflux/v2
maintainers:
  - name: trly
    email: trly@users.noreply.github.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
  - name: postgresql
    version: 12.12.4
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
