---
apiVersion: v2
appVersion: 5.0.2
description: Fully configurable Zwave to MQTT Gateway and Control Panel
name: zwavejs2mqtt
version: 5.4.3
kubeVersion: ">=1.16.0-0"
keywords:
  - zwave
  - mqtt
  - home-assistant
home: https://github.com/bjw-s/charts/tree/master/charts/stable/zwavejs2mqtt
icon: https://raw.githubusercontent.com/zwave-js/zwavejs2mqtt/v4.0.0/static/logo.png
sources:
  - https://github.com/zwave-js/zwavejs2mqtt
  - https://hub.docker.com/r/zwavejs/zwavejs2mqtt
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
