---
apiVersion: v2
appVersion: 8.0.7
description: seafile helm package
name: seafile
version: 3.3.0
kubeVersion: ">=1.16.0-0"
keywords:
  - seafile
home: https://github.com/bjw-s/charts/tree/master/charts/stable/seafile
icon: https://manual.seafile.com/media/seafile-transparent-1024.png
sources:
  - https://github.com/haiwen/seafile-docker
maintainers:
  - name: phybros
    email: 1985132+phybros@users.noreply.github.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.0
  - name: mariadb
    version: 11.5.7
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
