---
apiVersion: v2
appVersion: v4.3.0
description: Lychee is a free photo-management tool, which runs on your server or web-space
name: lychee
version: 7.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - lychee
  - photo
  - pictures
home: https://github.com/bjw-s/charts/tree/master/charts/stable/lychee
icon: https://avatars.githubusercontent.com/u/37916028?s=200&v=4
sources:
  - https://github.com/LycheeOrg/Lychee
  - https://hub.docker.com/r/lycheeorg/lychee
maintainers:
  - name: auricom
    email: bjw-s@xpander.eml.cc
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
