---
apiVersion: v2
appVersion: 2.2.2
description: Node-RED is low-code programming for event-driven applications
name: node-red
version: 10.3.2
kubeVersion: ">=1.16.0-0"
keywords:
  - nodered
  - node-red
home: https://github.com/bjw-s/charts/tree/master/charts/stable/node-red
icon: https://nodered.org/about/resources/media/node-red-icon-2.png
sources:
  - https://github.com/node-red/node-red-docker
  - https://github.com/bjw-s/charts/tree/master/charts/node-red
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
