---
apiVersion: v2
appVersion: v2.15.0
description: magic-mirror helm package
name: magic-mirror
version: 4.4.3
kubeVersion: ">=1.16.0-0"
keywords:
  - magic-mirror
home: https://github.com/bjw-s/charts/tree/master/charts/magic-mirror
sources:
  - https://github.com/MichMich/MagicMirror
  - https://hub.docker.com/r/bastilimbach/docker-magicmirror
maintainers:
  - name: brujoand
    email: anders@brujordet.no
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
