---
apiVersion: v2
appVersion: 4.6.0
description: Flood is a monitoring service for various torrent clients
name: flood
version: 7.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - flood
  - rtorrent
  - qbittorrent
  - transmission
home: https://github.com/bjw-s/charts/tree/master/charts/stable/flood
icon: https://raw.githubusercontent.com/jesec/flood/master/flood.svg
sources:
  - https://github.com/jesec/flood
  - https://hub.docker.com/r/jesec/flood
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.4.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
