---
apiVersion: v2
appVersion: 2021.2.1
description: Create live map data from Valetudo powered robots
name: icantbelieveitsnotvaletudo
version: 6.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - icantbelieveitsnotvaletudo
  - MQTT
  - valetudo
  - iot
home: https://github.com/bjw-s/charts/tree/master/charts/stable/icantbelieveitsnotvaletudo
icon: https://raw.githubusercontent.com/Hypfer/Valetudo/master/assets/logo/valetudo_logo_small.svg
sources:
  - https://github.com/Hypfer/ICantBelieveItsNotValetudo
  - https://github.com/bjw-s/charts/tree/master/charts/icantbelieveitsnotvaletudo
maintainers:
  - name: ishioni
    email: helm@movishell.pl
  - name: bjw-s
    email: me@bjw-s.dev
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.4.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
