---
apiVersion: v2
appVersion: cpu-2021.09.1
description: An AI API engine that serves pre-built models and custom models on multiple edge devices locally or on your private cloud
name: deepstack
version: 2.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - deepstack
  - ai
home: https://github.com/bjw-s/charts/tree/master/charts/stable/deepstack
icon: https://deepquest.sfo2.digitaloceanspaces.com/deepstackcc/static/img/deepstacklogo.png
sources:
  - https://deepstack.cc
  - https://github.com/johnolafenwa/DeepStack
  - https://github.com/robmarkcole/deepstack-ui
maintainers:
  - name: crutonjohn
    email: crutonjohn@pm.me
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
