---
apiVersion: v2
appVersion: v1.0.0.2255
description: Looks and smells like Sonarr but made for music
name: lidarr
version: 15.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - lidarr
  - torrent
  - usenet
home: https://github.com/bjw-s/charts/tree/master/charts/stable/lidarr
icon: https://github.com/lidarr/Lidarr/blob/develop/Logo/512.png?raw=true
sources:
  - https://github.com/Lidarr/Lidarr
  - https://github.com/bjw-s/container-images
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.4.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
