---
apiVersion: v2
appVersion: 1.26.1
description: Overseerr is a free and open source software application for managing requests for your media library. It integrates with your existing services such as Sonarr, Radarr and Plex!
name: overseerr
version: 6.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - overseerr
  - plex
  - sonarr
  - radarr
home: https://github.com/bjw-s/charts/tree/master/charts/stable/overseerr
icon: https://i.imgur.com/TMoEG7g.png
sources:
  - https://github.com/sct/overseerr
  - https://hub.docker.com/r/sctx/overseerr
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.4.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
