apiVersion: v2
appVersion: 1.0.0
description: ${CHARTNAME} helm package
name: ${CHARTNAME}
version: 2.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - ${CHARTNAME}
home: https://github.com/bjw-s/charts/tree/master/charts/stable/${CHARTNAME}
icon: https://${CHARTNAME}.org/icon
sources:
  - https://github.com/${CHARTNAME}/${CHARTNAME}-docker
maintainers:
  - name: ${CHARTNAME}
    email: ${CHARTNAME}@${CHARTNAME}.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.4.0
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial version
