---
apiVersion: v2
appVersion: 0.17.0
description: The to-do app to organize your life
name: vikunja
version: 7.2.0
keywords:
  - vikunja
  - to-do
  - tasks
  - calendar
  - kanban
home: https://github.com/bjw-s/charts/tree/master/charts/stable/vikunja
icon: https://s7.gifyu.com/images/GifCroppedTran.gif
sources:
  - https://kolaente.dev/vikunja/api
  - https://kolaente.dev/vikunja/frontend
  - https://hub.docker.com/r/vikunja/api
  - https://hub.docker.com/r/vikunja/frontend
  - https://vikunja.io/docs/
maintainers:
  - name: auricom
    email: bjw-s@xpander.eml.cc
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
  - name: postgresql
    version: 12.12.4
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
