---
apiVersion: v2
appVersion: version-eb59284b
description: TVheadend - a TV streaming server and digital video recorder
name: tvheadend
version: 6.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - tv
  - streaming
  - dvb
home: https://github.com/bjw-s/charts/tree/master/charts/stable/tvheadend
icon: https://raw.githubusercontent.com/tvheadend/tvheadend/master/src/webui/static/img/satip-icon120.png
sources:
  - https://github.com/tvheadend/tvheadend
maintainers:
  - name: mr-onion-2
  - name: bjw-s
    email: me@bjw-s.dev
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.4.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
