---
apiVersion: v2
appVersion: latest
description: Discord bot that provides metrics from a Discord server
name: promcord
version: 6.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - promcord
  - discord
  - metrics
home: https://github.com/bjw-s/charts/tree/master/charts/stable/promcord
sources:
  - https://github.com/nimarion/promcord
maintainers:
  - name: ChipWolf
    email: hello@chipwolf.uk
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.4.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
