---
apiVersion: v2
appVersion: v1.2.8
description: FlareSolverr is a proxy server to bypass Cloudflare protection
name: flaresolverr
version: 5.4.3
kubeVersion: ">=1.16.0-0"
keywords:
  - flaresolverr
  - jackett
home: https://github.com/bjw-s/charts/tree/master/charts/stable/flaresolverr
icon: https://raw.githubusercontent.com/FlareSolverr/FlareSolverr/master/resources/flaresolverr_logo.svg
sources:
  - https://github.com/FlareSolverr/FlareSolverr
  - https://hub.docker.com/r/flaresolverr/flaresolverr
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
