---
apiVersion: v2
appVersion: 2.00.18
description: Tdarr is a self hosted web-app for automating media library transcode/remux management and making sure your files are exactly how you need them to be in terms of codecs/streams/containers etc.
name: tdarr
version: 5.0.0
keywords:
  - transcoding
  - remux
  - media
  - video
home: https://github.com/bjw-s/charts/tree/master/charts/stable/tdarr
icon: https://s7.gifyu.com/images/GifCroppedTran.gif
sources:
  - https://www.github.com/HaveAGitGat/Tdarr
  - https://hub.docker.com/r/haveagitgat/tdarr/
  - https://tdarr.io/docs/
maintainers:
  - name: auricom
    email: bjw-s@xpander.eml.cc
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
