---
apiVersion: v2
appVersion: v1.6.1
description: Admision controller to change the default gateway and DNS server of PODs
name: pod-gateway
version: 5.6.2
kubeVersion: ">=1.16.0-0"
keywords:
  - pod-gateway
home: https://github.com/bjw-s/charts/tree/master/charts/stable/pod-gateway
icon: https://pod-gateway.org/icon
sources:
  - https://github.com/bjw-s/gateway-admision-controller
  - https://github.com/bjw-s/pod-gateway
maintainers:
  - name: angelnu
    email: git@angelnu.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
