---
apiVersion: v2
appVersion: 2.4.20
description: A free Microsoft OneDrive Client which supports OneDrive Personal, OneDrive for Business, OneDrive for Office365, and SharePoint
name: onedrive
version: 3.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - onedrive
  - filesync
home: https://github.com/bjw-s/charts/tree/master/charts/incubator/onedrive
icon: https://github.com/abraunegg/abraunegg.github.io/raw/master/images/linux_onedrive_logo.jpg
sources:
  - https://github.com/abraunegg/onedrive
maintainers:
  - name: wrmilling
    email: winston@milli.ng
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
