---
apiVersion: v2
appVersion: v0.23.0
description: Autobrr monitors IRC announce channels to get releases as soon as they are available with good filtering
name: autobrr
version: 2.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - autobrr
  - torrrent
home: https://github.com/bjw-s/charts/tree/master/charts/stable/autobrr
icon: https://avatars.githubusercontent.com/u/88781313?s=200&v=4
sources:
  - https://github.com/autobrr/autobrr
  - https://github.com/bjw-s/container-images
maintainers:
  - name: funkypenguin
    email: davidy@funkypenguin.co.nz
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.4.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
