---
apiVersion: v2
appVersion: 0.0.7
description: Take control over your live stream video by running it yourself. Streaming + chat out of the box.
name: owncast
version: 3.4.2
kubeVersion: ">=1.16.0-0"
keywords:
  - owncast
  - stream
  - open source
  - chat
home: https://github.com/bjw-s/charts/tree/master/charts/stable/owncast
icon: https://owncast.online/images/owncast-logo-1000x1000.png
sources:
  - https://owncast.online/
  - https://github.com/owncast/owncast
maintainers:
  - name: FlipEnergy
    email: dennis.zhang.nrg@gmail.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
