---
apiVersion: v2
appVersion: v0.13.1
description: Music streaming server / subsonic server API implementation
name: gonic
version: 7.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - music
  - subsonic
home: https://github.com/bjw-s/charts/tree/master/charts/stable/gonic
icon: https://raw.githubusercontent.com/sentriz/gonic/master/.github/logo.png
sources:
  - https://github.com/sentriz/gonic
  - https://hub.docker.com/r/sentriz/gonic
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
