---
apiVersion: v2
appVersion: 0.99.4
description: A comics/mangas server to serve/stream pages via API
name: komga
version: 3.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - komga
  - comics
  - mangas
  - server
home: https://github.com/bjw-s/charts/tree/master/charts/stable/komga
icon: https://komga.org/assets/media/logo.svg
sources:
  - https://komga.org/
  - https://github.com/gotson/komga
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.4.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
