---
apiVersion: v2
appVersion: v1.0.3
description: Bazarr is a companion application to Sonarr and Radarr. It manages and downloads subtitles based on your requirements
name: bazarr
version: 11.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - bazarr
  - radarr
  - sonarr
  - subtitles
  - usenet
  - torrent
home: https://github.com/bjw-s/charts/tree/master/charts/stable/bazarr
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/bazarr.png
sources:
  - https://github.com/morpheus65535/bazarr
  - https://github.com/bjw-s/container-images
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.4.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
