---
apiVersion: v2
appVersion: v3.2.2
description: Speedtest Exporter made in python using the official speedtest bin
name: speedtest-exporter
version: 6.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - speedtest-exporter
  - speedtest
home: https://github.com/bjw-s/charts/tree/master/charts/stable/speedtest-exporter
sources:
  - https://github.com/MiguelNdeCarvalho/speedtest-exporter/
maintainers:
  - name: onedr0p
    email: devin.kray@gmail.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.4.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
