---
apiVersion: v2
appVersion: version-2.5.201
description: Make documentation a joy to write using Wiki.js's beautiful and intuitive interface!
name: wikijs
version: 7.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - wiki
  - wikijs
home: https://github.com/bjw-s/charts/tree/master/charts/stable/wikijs
icon: https://static.requarks.io/logo/wikijs-butterfly.svg
sources:
  - https://hub.docker.com/r/linuxserver/wikijs/
  - https://github.com/Requarks/wiki
maintainers:
  - name: rolfberkenbosch
    email: rolf@berkenbosch.nl
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
