---
apiVersion: v2
appVersion: 4.37.0
description: Ghost is a blogging and publishing software
name: ghost
version: 2.3.0
kubeVersion: ">=1.19.0-0"
keywords:
  - ghost
  - blogging
home: https://github.com/bjw-s/charts/tree/master/charts/stable/ghost
icon: https://ghost.org/images/logos/logo-black-1.png
sources:
  - https://github.com/TryGhost/Ghost
  - https://github.com/TryGhost/Ghost-CLI
maintainers:
  - name: samip5
    email: sm+bjw-s+git@samip.fi
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.0
  - name: mariadb
    version: 11.5.7
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
