---
apiVersion: v2
appVersion: v3.4.20
description: Simple, private file sharing.
name: send
version: 3.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - send
home: https://github.com/bjw-s/charts/tree/master/charts/stable/send
icon: https://gitlab.com/timvisee/send/-/raw/master/assets/icon.svg
sources:
  - https://gitlab.com/timvisee/send
maintainers:
  - name: geraldwuhoo
    email: gerald@geraldwu.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.4.0
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.17.1
    condition: redis.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
