---
apiVersion: v2
appVersion: 0.12.3
description: "Anonaddy: Anonymous email forwarding"
name: anonaddy
version: 8.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - anonaddy
home: https://github.com/bjw-s/charts/tree/master/charts/stable/anonaddy
icon: https://avatars.githubusercontent.com/u/51450862?s=200&v=4?sanitize=true
sources:
  - https://github.com/anonaddy/docker
maintainers:
  - name: simoncaron
    email: simon.caron@pm.me
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
  - name: mariadb
    version: 11.5.7
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: redis
    version: 18.6.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `redis` chart dependency to version 17.1.7
