---
apiVersion: v2
appVersion: 4.6.1.0
description: Emby Server is a home media server
name: emby
version: 4.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - emby
  - jellyfin
  - plex
home: https://github.com/bjw-s/charts/tree/master/charts/stable/emby
icon: https://truecharts.org/_static/img/emby-icon.png
sources:
  - https://github.com/MediaBrowser
  - https://github.com/bjw-s/container-images/tree/main/apps/emby
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
