---
apiVersion: v2
appVersion: 1.2.0
description: Cert-Manager Webhook for DNSMadeEasy
name: dnsmadeeasy-webhook
version: 5.0.0
keywords:
  - cert-manager
  - dnsmadeeasy
  - letsencrypt
home: https://github.com/bjw-s/charts/tree/master/charts/stable/dnsmadeeasy-webhook
icon: https://pbs.twimg.com/profile_images/1759911243/dnsmeavatar_400x400.png
sources:
  - https://github.com/bjw-s/dnsmadeeasy-webhook
  - https://cert-manager.io
maintainers:
  - name: angelnu
    email: git@angelnu.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: v1.13.0
    condition: cert-manager.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
