---
apiVersion: v2
appVersion: '4.3'
description: Omada enables the network administrators to monitor and manage all the Omada products in the network with a centralized management platform.
name: omada-controller
version: 5.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - omada-controller
home: https://github.com/bjw-s/charts/tree/master/charts/stable/omada-controller
icon: https://www.tp-link.com/assets/images/icon/logo-white.svg
sources:
  - https://github.com/mbentley/docker-omada-controller
  - https://github.com/bjw-s/charts/tree/master/charts/omada-controller
maintainers:
  - name: charlie-haley
    email: charlie-haley@users.noreply.github.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.4.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
