---
apiVersion: v2
appVersion: 0.10.0-amd64
description: NVR With Realtime Object Detection for IP Cameras
name: frigate
version: 9.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - frigate
  - nvr
  - tensorflow
  - coral
  - ml
  - machine-learning
home: https://github.com/bjw-s/charts/tree/master/charts/stable/frigate
icon: https://github.com/blakeblackshear/frigate/blob/master/docs/static/img/frigate.png
sources:
  - https://github.com/blakeblackshear/frigate
maintainers:
  - name: billimek
    email: jeff@billimek.com
  - name: PixelJonas
    email: 5434875+PixelJonas@users.noreply.github.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
