---
apiVersion: v2
appVersion: "2021.06.01"
description: DSMR-protocol reader, telegram data storage and energy consumption visualizer.
name: dsmr-reader
version: 7.0.2
kubeVersion: ">=1.16.0-0"
keywords:
  - dsmr-reader
  - energy
home: https://github.com/bjw-s/charts/tree/master/charts/stable/dsmr-reader
icon: https://avatars2.githubusercontent.com/u/57727360?s=400&v=4
sources:
  - https://github.com/dsmrreader/dsmr-reader
  - https://github.com/xirixiz/dsmr-reader-docker
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
  - name: postgresql
    version: 12.5.9
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
