---
apiVersion: v2
appVersion: 1.0.5.2
description: Recipes is a Django application to manage, tag and search recipes using either built in models or external storage providers hosting PDF's, Images or other files.
name: recipes
version: 6.6.2
kubeVersion: ">=1.16.0-0"
keywords:
  - recipes
  - cooking
home: https://github.com/bjw-s/charts/tree/master/charts/stable/recipes
icon: https://raw.githubusercontent.com/vabene1111/recipes/develop/docs/logo_color.svg
sources:
  - https://github.com/vabene1111/recipes
  - https://hub.docker.com/r/vabene1111/recipes
maintainers:
  - name: auricom
    email: bjw-s@xpander.eml.cc
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
