---
apiVersion: v2
appVersion: 1.3.5
description: A minimalist, open source online pastebin running on an Nginx, php-fpm & Alpine Linux stack
name: privatebin
version: 4.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - privatebin
  - pastebin
home: https://github.com/bjw-s/charts/tree/master/charts/incubator/privatebin
icon: https://privatebin.info/theme/img/icon.svg
sources:
  - https://github.com/PrivateBin/PrivateBin
  - https://github.com/PrivateBin/docker-nginx-fpm-alpine
maintainers:
  - name: psych0d0g
    email: psych0d0g@users.noreply.github.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.4.0
  - name: postgresql
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
