---
apiVersion: v2
appVersion: 2.4.2
description: A self hostable application for saving web pages, freely.
name: wallabag
version: 9.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - wallabag
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/wallabag
icon: "https://raw.githubusercontent.com/wallabag/logo/master/app-android/logo-app-android-icon-bg-white-512.png"
sources:
  - https://github.com/wallabag/docker
  - https://hub.docker.com/wallabag/wallabag
maintainers:
  - name: Patricol
    url: https://patricol.co/
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 4.5.2
  - name: redis
    version: 17.11.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: 12.5.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mariadb
    version: 11.5.7
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
