---
apiVersion: v2
appVersion: v2.2.0.200
description: M3U Proxy for Plex DVR and Emby Live TV.
name: xteve
version: 8.4.2
kubeVersion: ">=1.16.0-0"
keywords:
  - xteve
  - iptv
  - plex
  - emby
home: https://github.com/bjw-s/charts/tree/master/charts/stable/xteve
icon: https://raw.githubusercontent.com/xteve-project/xTeVe/master/html/img/logo_b_880x200.jpg
sources:
  - https://github.com/xteve-project/xTeVe
  - https://github.com/bjw-s/container-images
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
