---
apiVersion: v2
appVersion: 1.1.1
description: Prometheus NUT Exporter a service monitor to send NUT server metrics to a Prometheus instance.
name: prometheus-nut-exporter
version: 6.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - nut
  - prometheus
home: https://github.com/bjw-s/charts/tree/master/charts/stable/prometheus-nut-exporter
icon: https://www.iconfinder.com/data/icons/wpzoom-developer-icon-set/500/125-512.png
sources:
  - https://github.com/HON95/prometheus-nut-exporter
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.4.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
