---
apiVersion: v2
appVersion: v7.1.68
description: Ubiquiti Network's Unifi Controller
name: unifi
version: 6.1.1
keywords:
  - ubiquiti
  - unifi
home: https://github.com/bjw-s/charts/tree/master/charts/stable/unifi
icon: https://prd-www-cdn.ubnt.com/static/favicon-152.png
sources:
  - https://github.com/jacobalberty/unifi-docker
maintainers:
  - name: billimek
    email: jeff@billimek.com
  - name: mcronce
    email: mike@quadra-tec.net
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
  - name: mongodb
    version: 13.15.1
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
