---
apiVersion: v2
appVersion: version-v0.5.3
description: Mylar is the automated Comic Book downloader (cbr/cbz) for use with various download clients.
name: mylar
version: 5.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - mylar
home: https://github.com/bjw-s/charts/tree/master/charts/stable/mylar
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/mylar-icon.png
sources:
  - https://github.com/mylar3/mylar3
  - https://github.com/linuxserver/docker-mylar3
  - https://github.com/bjw-s/charts/tree/master/charts/mylar
maintainers:
  - name: Patricol
    url: https://patricol.co/
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
