---
apiVersion: v2
appVersion: 14.2.5
description: nightscout helm package
name: nightscout
version: 2.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - nightscout
home: https://github.com/bjw-s/charts/tree/master/charts/stable/nightscout
icon: https://github.com/nightscout/cgm-remote-monitor/blob/master/static/images/favicon-96x96.png
sources:
  - https://github.com/nightscout/nightscout-docker
maintainers:
  - name: nchilder
    email: nchilder@redhat.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.4.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
