---
apiVersion: v2
appVersion: 3.2.0
description: openhab helm package
name: openhab
version: 1.5.3
kubeVersion: ">=1.16.0-0"
keywords:
  - openhab
home: https://github.com/bjw-s/charts/tree/master/charts/stable/openhab
icon: https://www.openhab.org/openhab-logo-square.png
sources:
  - https://hub.docker.com/r/openhab/openhab
maintainers:
  - name: reitermarkus
    email: me@reitermark.us
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
