---
apiVersion: v2
appVersion: version-5.6.14
description: "Firefly III: a personal finances manager"
name: firefly-iii
version: 1.2.0
kubeVersion: ">=1.16.0-0"
keywords:
  - firefly-iii
  - firefly
home: "https://github.com/k8s-at-home/charts/tree/master/charts/stable/firefly-iii"
icon: "https://www.firefly-iii.org/assets/logo/color.png"
sources:
  - https://github.com/firefly-iii/firefly-iii
maintainers:
  - name: "bikram990"
    url: "https://github.com/bikram990"
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 4.5.2
  - name: mariadb
    version: 11.5.7
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: postgresql
    version: 11.9.13
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.11.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `redis` chart dependency to version 17.1.7
