---
apiVersion: v2
appVersion: 2.2.0
description: A minimal forward authentication service that provides OAuth/SSO login and authentication for the traefik reverse proxy/load balancer
name: traefik-forward-auth
version: 2.2.2
kubeVersion: ">=1.16.0-0"
keywords:
  - traefik
  - traefik-forward-auth
  - oauth
  - oauth2
  - oidc
home: https://github.com/bjw-s/charts/tree/master/charts/stable/traefik-forward-auth
sources:
  - https://github.com/thomseddon/traefik-forward-auth
  - https://hub.docker.com/r/thomseddon/traefik-forward-auth
maintainers:
  - name: DirtyCajunRice
    email: nick@cajun.pro
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
