---
apiVersion: v2
appVersion: latest
description: Simple text sharing
name: haste-server
version: 3.4.3
kubeVersion: ">=1.16.0-0"
keywords:
  - haste
  - hastebin
  - haste-server
  - pastebin
home: https://github.com/bjw-s/charts/tree/master/charts/stable/haste
icon: https://raw.githubusercontent.com/nicholaswilde/helm-charts/main/images/haste.png
sources:
  - https://github.com/seejohnrun/haste-server
  - https://github.com/bjw-s/container-images
maintainers:
  - name: rwaltr
    email: rwalt@pm.me
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
