---
apiVersion: v2
appVersion: 6.1.0
description: OpenEMR is the most popular open source electronic health records and medical practice management solution.
name: openemr
version: 7.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - openemr
  - health
  - medical
  - healthcare
  - emr
home: https://github.com/bjw-s/charts/tree/master/charts/stable/openemr
icon: https://avatars.githubusercontent.com/u/283089?s=200&v=4
sources:
  - https://github.com/openemr/openemr
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
  - name: mariadb
    version: 14.1.1
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
