---
apiVersion: v2
appVersion: 10.8.1
description: Jellyfin is a Free Software Media System
name: jellyfin
version: 9.5.4
kubeVersion: ">=1.16.0-0"
keywords:
  - jellyfin
  - plex
  - emby
home: https://github.com/bjw-s/charts/tree/master/charts/stable/jellyfin
icon: https://raw.githubusercontent.com/jellyfin/jellyfin-ux/master/branding/SVG/icon-solid-black.svg
sources:
  - https://hub.docker.com/r/jellyfin/jellyfin
  - https://github.com/jellyfin/jellyfin
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
