---
apiVersion: v2
appVersion: 1.5.0
description: beets helm package
name: beets
version: 1.4.2
kubeVersion: ">=1.16.0-0"
keywords:
  - beets
home: https://github.com/bjw-s/charts/tree/master/charts/stable/beets
icon: https://pbs.twimg.com/profile_images/934307246/logo-square_400x400.png
sources:
  - https://github.com/beetbox/beets
  - https://github.com/linuxserver/docker-beets
maintainers:
  - name: dangmai
    email: contact@dangmai.net
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
