---
apiVersion: v2
appVersion: v3.7.1
description: multus CNI allows multiple NICs per pod
name: multus
version: 3.5.2
kubeVersion: ">=1.16.0-0"
keywords:
  - multus
home: https://github.com/bjw-s/charts/tree/master/charts/stable/multus
icon: https://multus.org/icon
sources:
  - https://github.com/k8snetworkplumbingwg/multus-cni
maintainers:
  - name: angelnu
    email: git@angelnu.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
