---
apiVersion: v2
description: A KaH-common powered chart template. This can be useful for small projects that don't have their own chart.
name: kah-common-chart
version: 1.2.3
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
