---
apiVersion: v2
appVersion: 1.0.0
description: Simple and generic Prometheus exporter for MQTT. Tested with Mosquitto MQTT and Xiaomi sensors.
name: mqtt-exporter
version: 2.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - zigbee2mqtt
  - prometheus
home: https://github.com/bjw-s/charts/tree/master/charts/stable/mqtt-exporter
icon: https://static.veritone.com/assets/favicon/favicon.ico
sources:
  - https://github.com/kpetremann/mqtt-exporter
  - https://hub.docker.com/r/kpetrem/mqtt-exporter
maintainers:
  - name: philipp
    email: phil@hellmi.de
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
