---
apiVersion: v2
appVersion: version-v1.20.0
description: Healthchecks is a cron job monitoring service. It listens for HTTP requests and email messages ("pings") from your cron jobs and scheduled tasks ("checks"). When a ping does not arrive on time, Healthchecks sends out alerts.
name: healthchecks
version: 4.4.3
keywords:
  - cron
  - monitoring
  - alert
home: https://github.com/bjw-s/charts/tree/master/charts/stable/healthchecks
icon: https://raw.githubusercontent.com/healthchecks/healthchecks/master/stuff/logo.svg?raw=true
sources:
  - https://github.com/healthchecks/healthchecks
  - https://hub.docker.com/r/linuxserver/healthchecks
maintainers:
  - name: auricom
    email: bjw-s@xpander.eml.cc
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
