---
apiVersion: v2
appVersion: 0.3.0
description: Neolink - RTSP bridge to Reolink IP cameras
name: neolink
version: 6.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - reolink
  - rtsp
home: https://github.com/bjw-s/charts/tree/master/charts/stable/neolink
sources:
  - https://github.com/thirtythreeforty/neolink
maintainers:
  - name: mr-onion-2
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
