---
apiVersion: v2
appVersion: v1.8723.0
description: Tiny Tiny RSS is a free and open source web-based news feed (RSS/Atom) reader and aggregator
name: tt-rss
version: 7.0.1
kubeVersion: ">=1.16.0-0"
keywords:
  - tt-rss
home: https://github.com/bjw-s/charts/tree/master/charts/stable/tt-rss
icon: https://git.tt-rss.org/fox/tt-rss/raw/branch/master/images/favicon-72px.png
sources:
  - https://git.tt-rss.org/fox/tt-rss
maintainers:
  - name: angelnu
    email: git@angelnu.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.0.3
  - name: postgresql
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.5.0
